<?php 
	header('Content-Type: text/html; charset=utf-8'); 
?> 
<!doctype html>
<html lang="en"> 
<head>
<meta charset="utf-8"> 
 <link href="_css/main.css" rel="stylesheet" media="screen, projection">
 <title>Earthquake</title>
</head> 
<body>
	<header>
    <nav>
    	<ul>
        <li><a href="index.php" title="HOME" class="current">Home</a></li>
        <li><a href="nanar.php" title="NANAR">Infomation</a></li>
        <li><a href="#" title=""></a></li>
        <li><a href="#" title=""></a></li>
        </ul>
    </nav>
    </header>
	<h1>Earthquake</h1>
    
 <p>An earthquake (also known as a quake, tremor or temblor) is the result of a sudden release of energy
in the Earth's  crust that creates seismic waves. The seismicity, seismism or seismic activity of an area refers to the
frequency,   type and size of earthquakes experienced over a period of time.</p> 
<p>Earthquakes are measured usingobservations from seismometers. The moment magnitude is the most common scale on which earthquakes larger than
approximately 5 are reported for the entire globe. The more numerous earthquakes smaller than magnitude 5 reported by
national seismological observatories are measured mostly on the local magnitude scale, also referred to as the Richter
scale. These two scales are numerically similar over their range of validity. Magnitude 3 or lower earthquakes are
mostly almost imperceptible or weak and magnitude 7 and over potentially cause serious damage over larger areas,
depending on their depth. The largest earthquakes in historic times have been of magnitude slightly over 9, although
there is no limit to the possible magnitude. The most recent large earthquake of magnitude 9.0 or larger was a 9.0
magnitude earthquake in Japan in 2011 (as of October 2012), and it was the largest Japanese earthquake since records
began. Intensity of shaking is measured on the modified Mercalli scale. The shallower an earthquake, the more damage to
structures it causes, all else being equal.</p>

<p> At the Earth's surface, earthquakes manifest themselves by shaking and sometimes displacement of the ground. When
the epicenter of a large earthquake is located offshore, the seabed may be displaced sufficiently to cause a tsunami.
Earthquakes can also trigger landslides, and occasionally volcanic activity. In its most general sense, the word
earthquake is used to describe any seismic event — whether natural or caused by humans — that generates seismic waves.
Earthquakes are caused mostly by rupture of geological faults, but also by other events such as volcanic activity,
landslides, mine blasts, and nuclear tests. An earthquake's point of initial rupture is called its focus or hypocenter.
The epicenter is the point at ground level directly above the hypocenter.</p> 
<h2>Naturally occurring earthquakes</h2>
<p>Tectonic earthquakes occur anywhere in the earth where there is sufficient stored elastic strain energy to drive
fracture propagation along a fault plane. The sides of a fault move past each other smoothly and aseismically only if
there are no irregularities or asperities along the fault surface that increase the frictional resistance. Most fault
surfaces do have such asperities and this leads to a form of stick-slip behaviour. Once the fault has locked, continued
relative motion between the plates leads to increasing stress and therefore, stored strain energy in the volume around
the fault surface. This continues until the stress has risen sufficiently to break through the asperity, suddenly
allowing sliding over the locked portion of the fault, releasing the stored energy. This energy is released as a
combination of radiated elastic strain seismic waves, frictional heating of the fault surface, and cracking of the rock,
thus causing an earthquake. This process of gradual build-up of strain and stress punctuated by occasional sudden
earthquake failure is referred to as the elastic-rebound theory. It is estimated that only 10 percent or less of an
earthquake's total energy is radiated as seismic energy. Most of the earthquake's energy is used to power the earthquake
fracture growth or is converted into heat generated by friction. Therefore, earthquakes lower the Earth's available
elastic potential energy and raise its temperature, though these changes are negligible compared to the conductive and
convective flow of heat out from the Earth's deep interior.[2]</p>

<h2>Earthquake fault types</h2>
<p>There are three main types of fault, all of which may cause an earthquake: normal, reverse (thrust) and strike-slip. Normal and reverse faulting are examples of dip-slip, where the displacement along the fault is in the direction of dip and movement on them involves a vertical component. Normal faults occur mainly in areas where the crust is being extended such as a divergent boundary. Reverse faults occur in areas where the crust is being shortened such as at a convergent boundary. Strike-slip faults are steep structures where the two sides of the fault slip horizontally past each other; transform boundaries are a particular type of strike-slip fault. Many earthquakes are caused by movement on faults that have components of both dip-slip and strike-slip; this is known as oblique slip.
<p>Reverse faults, particularly those along convergent plate boundaries are associated with the most powerful earthquakes, including almost all of those of magnitude 8 or more. Strike-slip faults, particularly continental transforms can produce major earthquakes up to about magnitude 8. Earthquakes associated with normal faults are generally less than magnitude 7.</p>
<p>This is so because the energy released in an earthquake, and thus its magnitude, is proportional to the area of the fault that ruptures[3] and the stress drop. Therefore, the longer the length and the wider the width of the faulted area, the larger the resulting magnitude. The topmost, brittle part of the Earth's crust, and the cool slabs of the tectonic plates that are descending down into the hot mantle, are the only parts of our planet which can store elastic energy and release it in fault ruptures. Rocks hotter than about 300 degrees Celsius flow in response to stress; they do not rupture in earthquakes.[4][5] The maximum observed lengths of ruptures and mapped faults, which may break in one go are approximately 1000 km. Examples are the earthquakes in Chile, 1960; Alaska, 1957; Sumatra, 2004, all in subduction zones. The longest earthquake ruptures on strike-slip faults, like the San Andreas Fault (1857, 1906), the North Anatolian Fault in Turkey (1939) and the Denali Fault in Alaska (2002), are about half to one third as long as the lengths along subducting plate margins, and those along normal faults are even shorter.</p>


<p>The most important parameter controlling the maximum earthquake magnitude on a fault is however not the maximum available length, but the available width because the latter varies by a factor of 20. Along converging plate margins, the dip angle of the rupture plane is very shallow, typically about 10 degrees.[6] Thus the width of the plane within the top brittle crust of the Earth can become 50 to 100 km (Japan, 2011; Alaska, 1964), making the most powerful earthquakes possible.</p>
<p>Strike-slip faults tend to be oriented near vertically, resulting in an approximate width of 10 km within the brittle crust,[7] thus earthquakes with magnitudes much larger than 8 are not possible. Maximum magnitudes along many normal faults are even more limited because many of them are located along spreading centers, as in Iceland, where the thickness of the brittle layer is only about 6 km.[8][9]</p>
<p>In addition, there exists a hierarchy of stress level in the three fault types. Thrust faults are generated by the highest, strike slip by intermediate, and normal faults by the lowest stress levels.[10] This can easily be understood by considering the direction of the greatest principal stress, the direction of the force that 'pushes' the rock mass during the faulting. In the case of normal faults, the rock mass is pushed down in a vertical direction, thus the pushing force (greatest principal stress) equals the weight of the rock mass itself. In the case of thrusting, the rock mass 'escapes' in the direction of the least principal stress, namely upward, lifting the rock mass up, thus the overburden equals the least principal stress. Strike-slip faulting is intermediate between the other two types described above. This difference in stress regime in the three faulting environments can contribute to differences in stress drop during faulting, which contributes to differences in the radiated energy, regardless of fault dimensions.</p>

<h2>Earthquakes away from plate boundaries</h2>
<p>Where plate boundaries occur within continental lithosphere, deformation is spread out over a much larger area than the plate boundary itself. In the case of the San Andreas fault continental transform, many earthquakes occur away from the plate boundary and are related to strains developed within the broader zone of deformation caused by major irregularities in the fault trace (e.g., the "Big bend" region). The Northridge earthquake was associated with movement on a blind thrust within such a zone. Another example is the strongly oblique convergent plate boundary between the Arabian and Eurasian plates where it runs through the northwestern part of the Zagros mountains. The deformation associated with this plate boundary is partitioned into nearly pure thrust sense movements perpendicular to the boundary over a wide zone to the southwest and nearly pure strike-slip motion along the Main Recent Fault close to the actual plate boundary itself. This is demonstrated by earthquake focal mechanisms.[11]
All tectonic plates have internal stress fields caused by their interactions with neighbouring plates and sedimentary loading or unloading (e.g. deglaciation[12]). These stresses may be sufficient to cause failure along existing fault planes, giving rise to intraplate earthquakes.[13]</p>
<h2>Shallow-focus and deep-focus earthquakes</h2>
<p>The majority of tectonic earthquakes originate at the ring of fire in depths not exceeding tens of kilometers. Earthquakes occurring at a depth of less than 70 km are classified as 'shallow-focus' earthquakes, while those with a focal-depth between 70 and 300 km are commonly termed 'mid-focus' or 'intermediate-depth' earthquakes. In subduction zones, where older and colder oceanic crust descends beneath another tectonic plate, deep-focus earthquakes may occur at much greater depths (ranging from 300 up to 700 kilometers).[14] These seismically active areas of subduction are known as Wadati-Benioff zones. Deep-focus earthquakes occur at a depth where the subducted lithosphere should no longer be brittle, due to the high temperature and pressure. A possible mechanism for the generation of deep-focus earthquakes is faulting caused by olivine undergoing a phase transition into a spinel structure.[15]</p>
<h2>Earthquakes and volcanic activity</h2>
<p> Earthquakes often occur in volcanic regions and are caused there, both by tectonic faults and the movement of magma in volcanoes. Such earthquakes can serve as an early warning of volcanic eruptions, as during the Mount St. Helens eruption of 1980.[16] Earthquake swarms can serve as markers for the location of the flowing magma throughout the volcanoes. These swarms can be recorded by seismometers and tiltmeters (a device that measures ground slope) and used as sensors to predict imminent or upcoming eruptions.[17]</p>
<h2>Rupture dynamics</h2>
<p>A tectonic earthquake begins by an initial rupture at a point on the fault surface, a process known as nucleation. The scale of the nucleation zone is uncertain, with some evidence, such as the rupture dimensions of the smallest earthquakes, suggesting that it is smaller than 100 m while other evidence, such as a slow component revealed by low-frequency spectra of some earthquakes, suggest that it is larger. The possibility that the nucleation involves some sort of preparation process is supported by the observation that about 40% of earthquakes are preceded by foreshocks. Once the rupture has initiated it begins to propagate along the fault surface. The mechanics of this process are poorly understood, partly because it is difficult to recreate the high sliding velocities in a laboratory. Also the effects of strong ground motion make it very difficult to record information close to a nucleation zone.[18]
Rupture propagation is generally modeled using a fracture mechanics approach, likening the rupture to a propagating mixed mode shear crack. The rupture velocity is a function of the fracture energy in the volume around the crack tip, increasing with decreasing fracture energy. The velocity of rupture propagation is orders of magnitude faster than the displacement velocity across the fault. Earthquake ruptures typically propagate at velocities that are in the range 70–90% of the S-wave velocity and this is independent of earthquake size. A small subset of earthquake ruptures appear to have propagated at speeds greater than the S-wave velocity. These supershear earthquakes have all been observed during large strike-slip events. The unusually wide zone of coseismic damage caused by the 2001 Kunlun earthquake has been attributed to the effects of the sonic boom developed in such earthquakes. Some earthquake ruptures travel at unusually low velocities and are referred to as slow earthquakes. A particularly dangerous form of slow earthquake is the tsunami earthquake, observed where the relatively low felt intensities, caused by the slow propagation speed of some great earthquakes, fail to alert the population of the neighbouring coast, as in the 1896 Meiji-Sanriku earthquake.[18]</p>
<h2>Earthquake clusters</h2>
<p>Most earthquakes form part of a sequence, related to each other in terms of location and time.[23] Most earthquake clusters consist of small tremors that cause little to no damage, but there is a theory that earthquakes can recur in a regular pattern.[24]</p>
<h2>Aftershocks</h2>
<p>An aftershock is an earthquake that occurs after a previous earthquake, the mainshock. An aftershock is in the same region of the main shock but always of a smaller magnitude. If an aftershock is larger than the main shock, the aftershock is redesignated as the main shock and the original main shock is redesignated as a foreshock. Aftershocks are formed as the crust around the displaced fault plane adjusts to the effects of the main shock.[23]</p>
<h2>Earthquake swarms</h2>
<p>Earthquake swarms are sequences of earthquakes striking in a specific area within a short period of time. They are different from earthquakes followed by a series of aftershocks by the fact that no single earthquake in the sequence is obviously the main shock, therefore none have notable higher magnitudes than the other. An example of an earthquake swarm is the 2004 activity at Yellowstone National Park.[25] In August 2012, a swarm of earthquakes shook Southern California's Imperial Valley, showing the most recorded activity in the area since the 1970s.[26]</p>
<h2>Earthquake storms</h2>
<p>Sometimes a series of earthquakes occur in a sort of earthquake storm, where the earthquakes strike a fault in clusters, each triggered by the shaking or stress redistribution of the previous earthquakes. Similar to aftershocks but on adjacent segments of fault, these storms occur over the course of years, and with some of the later earthquakes as damaging as the early ones. Such a pattern was observed in the sequence of about a dozen earthquakes that struck the North Anatolian Fault in Turkey in the 20th century and has been inferred for older anomalous clusters of large earthquakes in the Middle East.[27][28]</p>

	<footer>
    </footer>	  
  </body>
 <html>
	